version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    volumes:
      - "./keycloak/data:/opt/keycloak/data"
      - "./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf"
      - "./ssl/certs/:/etc/ssl/moodle/"
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "password"
  synapse:
    image: "matrixdotorg/synapse:v1.78.0"
    volumes:
      - "./synapse_data:/data:rw"
      - "./ssl/certs/:/etc/ssl/moodle/"
    environment:
      SYNAPSE_SERVER_NAME: "synapse"
      SYNAPSE_REPORT_STATS: "yes"
    ports:
      - "8008:8008"
      - "8448:8448"
    depends_on:
      - keycloak
    restart: on-failure
  element:
    image: vectorim/element-web
    volumes:
      - "./element_data/config.json:/app/config.json"
      - "./element_data/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl/certs/:/etc/ssl/moodle/"
    ports:
      - "8081:8081"
    depends_on:
      - synapse
networks:
  default:
    ipam:
      driver: default
